In [1]:
import pandas as pd
# Dış ortam hava durumu verisi okuma
df_hava = pd.read_csv('../data/meteo.csv')
# Verinin ilk 5 satırını yazdır
df_hava.head()

,time,AbsHumOut,Iglob,PARout,Pyrgeo,RadSum,Rain,Rhout,Tout,Winddir,Windsp
0,8/14/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8/14/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8/14/2018,13.369189,0.0,0.0,-32.000000,0.0,0.0,87.8,17.7,32.0,3.2
3,8/14/2018,13.389380,0.0,0.0,-36.000000,0.0,0.0,87.4,17.8,32.0,3.2
4,8/14/2018,13.455197,0.0,1.0,-38.999999,0.0,0.0,87.3,17.9,32.0,3.2

In [2]:
# Veri seti hakkında genel bilgiler
print("Veri Seti Bilgileri:")
df_hava.info()
# Hangi sütunda kaç tane boş (NaN) veri var
print("\nBoş Veri (NaN) Sayıları:")
print(df_hava.isnull().sum())

# İçinde NaN bulunan ilk hatalı satırları veri setinden sil
df_hava_temiz = df_hava.dropna()

# Temizlenmiş verinin ilk 5 satırı
df_hava_temiz.head()

Veri Seti Bilgileri:
<class 'pandas.DataFrame'>
RangeIndex: 33133 entries, 0 to 33132
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   time       33133 non-null  str
 1   AbsHumOut  32991 non-null  float64
 2   Iglob      32992 non-null  float64
 3   PARout     32992 non-null  float64
 4   Pyrgeo     32992 non-null  float64
 5   RadSum     32991 non-null  float64
 6   Rain       32992 non-null  float64
 7   Rhout      32991 non-null  float64
 8   Tout       32991 non-null  float64
 9   Winddir    32992 non-null  float64
 10  Windsp     32991 non-null  float64
dtypes: float64(10), str(1)
memory usage: 2.8 MB

Boş Veri (NaN) Sayıları:
time           0
AbsHumOut    142
Iglob        141
PARout       141
Pyrgeo       141
RadSum       142
Rain         141
Rhout        142
Tout         142
Winddir      141
Windsp       142
dtype: int64

,time,AbsHumOut,Iglob,PARout,Pyrgeo,RadSum,Rain,Rhout,Tout,Winddir,Windsp
2,8/14/2018,13.369189,0.0,0.0,-32.000000,0.0,0.0,87.8,17.7,32.0,3.2
3,8/14/2018,13.389380,0.0,0.0,-36.000000,0.0,0.0,87.4,17.8,32.0,3.2
4,8/14/2018,13.455197,0.0,1.0,-38.999999,0.0,0.0,87.3,17.9,32.0,3.2
5,8/14/2018,13.465462,0.0,1.0,-28.000001,0.0,0.0,87.9,17.8,32.0,3.2
6,8/14/2018,13.435029,0.0,1.0,-23.000000,0.0,0.0,87.7,17.8,32.0,3.2